# -*- coding: utf-8 -*-
"""Model_DenseNet_121.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gmbe8d3T1Ogab08HHFEcpwuLwXZVFRo5

# DenseNet-121 — training + reusable evaluation

This notebook trains a DenseNet-121 transfer model **and** runs a full evaluation on it. The
evaluation is written once as a function (`evaluate_model`) and can be applied to **two** models:

- the **freshly trained** model produced by this run (the default "Run all" path), and
- an **optional model loaded from Google Drive** — useful to score a model trained in an earlier
  session without retraining.

By default the *load* cell (Section "Optional: load a saved model") is
**commented out**, so **Run all** simply trains a fresh model and evaluates it. Evaluation only uses loaded model as fallback.
"""

# Colab: load Kaggle credentials from Colab Secrets.
import os
try:
    from google.colab import userdata
    os.environ["KAGGLE_USERNAME"] = userdata.get("KAGGLE_USERNAME")
    os.environ["KAGGLE_KEY"]      = userdata.get("KAGGLE_KEY")
    print("Kaggle credentials loaded from Colab Secrets.")
except ModuleNotFoundError:
    pass  # not on Colab - falls back to local ~/.kaggle/kaggle.json

"""## Mount Google Drive (necessary only for saving and loading trained models)"""

# Colab: Mount Google Drive and access shared folder
from pathlib import Path
try:
    from google.colab import drive
    drive.mount("/content/drive")
    SHARED = Path("/content/drive/MyDrive/Liora_Plant_Recognition_shared")  # Name of Target Folder
    assert SHARED.exists(), (
        "Folder not found. Please create link to shared folder.")
    DRIVE_DIR = SHARED / "model_densenet"     # name of model file
    DRIVE_DIR.mkdir(parents=True, exist_ok=True)
    print("Save to: ", DRIVE_DIR)
except ModuleNotFoundError:
    DRIVE_DIR = RESULTS   # local

# Commented out IPython magic to ensure Python compatibility.
# Imports, seeds, paths, and the run configuration
from pathlib import Path
from collections import deque
import os, time, random, json
import numpy as np, pandas as pd
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from tensorflow.keras.applications import DenseNet121
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.dummy import DummyClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (f1_score, recall_score, accuracy_score,
                             confusion_matrix, classification_report)

sns.set_theme()
SEED = 42
random.seed(SEED); np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

# paths
BASE       = Path.home() / "plant_recognition"
PV_DIR     = BASE / "plantvillage"
RESULTS    = BASE / "step3_baseline"; RESULTS.mkdir(parents=True, exist_ok=True)
SPLIT_CSV  = {s: RESULTS / f"split_{s}.csv" for s in ("train", "val", "test")}
TAB_CSV    = {s: RESULTS / f"tabular_{s}.csv" for s in ("trainsample", "val")}
IMG_EXTS   = {".jpg", ".jpeg", ".png", ".bmp", ".gif", ".tif", ".tiff"}

# run configuration (everything tunable in one place)
IMG_SIZE   = 128
BATCH_SIZE = 32
SPLIT      = (0.70, 0.15, 0.15)        # train / val / test
EPOCHS     = 20
TAB_TRAIN_PER_CLASS = 300
# DenseNet parameters
HEAD_EPOCHS  = 5                       # phase 1: train the new head with the backbone FROZEN
FT_EPOCHS    = 20                      # phase 2: fine-tune the backbone (EarlyStopping usually stops earlier)
HEAD_LR      = 1e-3                    # higher LR while only the head learns
FT_LR        = 1e-5                    # low LR for fine-tuning a pre-trained backbone

# Smoke test: flip to True for a ~2-min end-to-end dry run before the full training run.
SMOKE_TEST      = False
SMOKE_PER_CLASS = 60

gpus = tf.config.list_physical_devices("GPU")
print(f"TensorFlow {tf.__version__} | GPU: {'YES - ' + gpus[0].name if gpus else 'NO (enable Runtime > GPU)'}")
print(f"Config: IMG_SIZE={IMG_SIZE}, BATCH={BATCH_SIZE}, EPOCHS={EPOCHS}, SMOKE_TEST={SMOKE_TEST}")

# Download raw PlantVillage from Kaggle (skips if PV_DIR is non-empty; needs kaggle.json)
if not PV_DIR.exists() or not any(PV_DIR.iterdir()):
    from kaggle.api.kaggle_api_extended import KaggleApi
    PV_DIR.mkdir(parents=True, exist_ok=True)
    api = KaggleApi(); api.authenticate()
    api.dataset_download_files("abdallahalidev/plantvillage-dataset",
                               path=str(PV_DIR), unzip=True, quiet=False)
    print("Downloaded to", PV_DIR)
else:
    print("Already present:", PV_DIR)

# Breadth-first search for the 'color' folder, then list the classes (sorted = canonical label order)
def locate(root, names, max_depth=4):
    q = deque([(root, 0)])
    while q:
        d, depth = q.popleft()
        if d.is_dir() and d.name.lower() in names:
            return d
        if d.is_dir() and depth < max_depth:
            for c in sorted(d.iterdir()):
                if c.is_dir():
                    q.append((c, depth + 1))
    return None

COLOR_DIR = locate(PV_DIR, {"color"})
assert COLOR_DIR is not None, "Could not find a 'color' folder under PV_DIR - check the path."
class_names = sorted([d.name for d in COLOR_DIR.iterdir() if d.is_dir()])
name2idx    = {n: i for i, n in enumerate(class_names)}       # label -> integer index (used everywhere)
n_classes   = len(class_names)
print("color dir:", COLOR_DIR)
print(f"classes: {n_classes}")
assert n_classes == 38, f"expected 38 classes, found {n_classes}"
print("first / last class:", class_names[0], "/", class_names[-1])

# Build (or load) the canonical file-level stratified split, then verify it
def enumerate_files(color_dir):
    paths, labels = [], []
    for c in class_names:
        for f in sorted((color_dir / c).iterdir()):
            if f.suffix.lower() in IMG_EXTS:
                paths.append(str(f)); labels.append(c)
    return np.array(paths), np.array(labels)

if all(p.exists() for p in SPLIT_CSV.values()):
    # Reuse the canonical split saved by an earlier run / a teammate -> guarantees identical splits
    dfs = {s: pd.read_csv(SPLIT_CSV[s]) for s in SPLIT_CSV}
    p_tr, y_tr = dfs["train"]["filepath"].values, dfs["train"]["label"].values
    p_val, y_val = dfs["val"]["filepath"].values, dfs["val"]["label"].values
    p_te, y_te = dfs["test"]["filepath"].values, dfs["test"]["label"].values
    print("Loaded saved split from CSV (canonical, shared across runs).")
else:
    paths, labels = enumerate_files(COLOR_DIR)
    print(f"enumerated {len(paths):,} image files")
    test_frac = SPLIT[2]
    val_frac_of_rest = SPLIT[1] / (SPLIT[0] + SPLIT[1])
    p_tr, p_te, y_tr, y_te = train_test_split(
        paths, labels, test_size=test_frac, stratify=labels, random_state=SEED)
    p_tr, p_val, y_tr, y_val = train_test_split(
        p_tr, y_tr, test_size=val_frac_of_rest, stratify=y_tr, random_state=SEED)
    for s, (pp, yy) in {"train": (p_tr, y_tr), "val": (p_val, y_val), "test": (p_te, y_te)}.items():
        pd.DataFrame({"filepath": pp, "label": yy}).to_csv(SPLIT_CSV[s], index=False)
    print("Built split with train_test_split x2 (stratified) and saved CSVs.")

# verify: sizes, every class present in each set, and no leakage across sets
print(f"\ntrain / val / test : {len(p_tr):,} / {len(p_val):,} / {len(p_te):,}"
      f"  ({len(p_tr)/(len(p_tr)+len(p_val)+len(p_te)):.0%} / "
      f"{len(p_val)/(len(p_tr)+len(p_val)+len(p_te)):.0%} / "
      f"{len(p_te)/(len(p_tr)+len(p_val)+len(p_te)):.0%})")
for nm, yy in [("train", y_tr), ("val", y_val), ("test", y_te)]:
    assert set(yy) == set(class_names), f"{nm} is missing classes!"
s_tr, s_val, s_te = set(p_tr), set(p_val), set(p_te)
assert s_tr.isdisjoint(s_val) and s_tr.isdisjoint(s_te) and s_val.isdisjoint(s_te), "LEAKAGE: sets overlap!"
print("verified: all 38 classes present in each split, and the three sets are disjoint (no leakage).")
print("NOTE: the test set is built here but is NOT used again - it is reserved for Deliverable 2.")

# Optional smoke-test subsample (train/val only; keeps the split logic intact)
def cap_per_class(paths, labels, cap, seed=SEED):
    rng = random.Random(seed); by = {}
    for p, l in zip(paths, labels): by.setdefault(l, []).append(p)
    op, ol = [], []
    for l, ps in by.items():
        sel = ps if len(ps) <= cap else rng.sample(ps, cap)
        op += sel; ol += [l] * len(sel)
    idx = np.arange(len(op)); rng.shuffle(idx)
    op, ol = np.array(op), np.array(ol)
    return op[idx], ol[idx]

if SMOKE_TEST:
    p_tr, y_tr   = cap_per_class(p_tr, y_tr, SMOKE_PER_CLASS)
    p_val, y_val = cap_per_class(p_val, y_val, max(20, SMOKE_PER_CLASS // 3))
    print(f"[SMOKE_TEST] reduced to train={len(p_tr):,}, val={len(p_val):,}")

# integer labels (canonical sorted order)
yi_tr  = np.array([name2idx[y] for y in y_tr],  dtype="int32")
yi_val = np.array([name2idx[y] for y in y_val], dtype="int32")

AUTOTUNE = tf.data.AUTOTUNE
def make_ds(paths, ilabels, training):
    ds = tf.data.Dataset.from_tensor_slices((paths, ilabels))
    def _load(path, lab):
        img = tf.io.read_file(path)
        img = tf.io.decode_image(img, channels=3, expand_animations=False)  # robust to jpg/png
        img = tf.image.resize(img, [IMG_SIZE, IMG_SIZE])                     # float, still 0-255
        img.set_shape([IMG_SIZE, IMG_SIZE, 3])
        return img, lab
    ds = ds.map(_load, num_parallel_calls=AUTOTUNE)
    if training:
        ds = ds.shuffle(min(2048, len(paths)), seed=SEED, reshuffle_each_iteration=True)
    return ds.batch(BATCH_SIZE).prefetch(AUTOTUNE)

train_ds = make_ds(p_tr, yi_tr, training=True)
val_ds   = make_ds(p_val, yi_val, training=False)   # order preserved -> lines up with yi_val for metrics

xb, yb = next(iter(train_ds))
print("batch images:", xb.shape, "| pixel range:", float(tf.reduce_min(xb)), "-", float(tf.reduce_max(xb)))
assert float(tf.reduce_max(xb)) > 1.5, "pixels should still be 0-255 here (normalisation is a model layer)"
print("pipelines ready (pixels kept 0-255; DenseNet normalisation is applied inside the model).")

# Balanced class weights from the TRAIN split -> dict {class_index: weight} for model.fit
weights = compute_class_weight(class_weight="balanced",
                               classes=np.arange(n_classes), y=yi_tr)
class_weight = {i: float(w) for i, w in enumerate(weights)}
top = sorted(class_weight.items(), key=lambda kv: kv[1], reverse=True)[:3]
print("weight range: {:.2f} (most common class) ... {:.2f} (rarest class)".format(
      min(class_weight.values()), max(class_weight.values())))
print("highest-weighted (rarest) classes:", [(class_names[i], round(w, 1)) for i, w in top])

"""## The model — DenseNet-121 pre-trained on ImageNet

- **Normalisation inside the model.** DenseNet's ImageNet weights expect its own pre-processing.
  We reproduce that with two plain, fully-serialisable Keras layers — `Rescaling(1/255)` then a
  `Normalization` with fixed ImageNet mean/variance.
- **Augmentation as train-only layers** (flip / small rotation / small zoom), identical to the baseline.
- **A small new head:** global average pooling → dropout → a 38-way softmax. The backbone provides the features; only the head is new.

We first build the model with the **backbone frozen** (`trainable=False`) for the head warm-up phase.

Transfer learning reuses features learned on 1.4M ImageNet images, which is exactly the
head-start a 38-class leaf-disease problem with rare classes needs.
"""

# DenseNet-121 transfer model: train-only augmentation + ImageNet normalisation + frozen backbone + small head
data_augment = models.Sequential([
    layers.RandomFlip("horizontal", seed=SEED),
    layers.RandomRotation(0.05, seed=SEED),
    layers.RandomZoom(0.05, seed=SEED),
], name="augment")   # train-only, as in the baseline

DN_MEAN = [0.485, 0.456, 0.406]
DN_STD  = [0.229, 0.224, 0.225]

base_model = DenseNet121(
    include_top=False,
    weights="imagenet",
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    pooling=None
    )
base_model.trainable = False     # phase 1: freeze backbone, only head learns

def build_densenet():
    inputs = layers.Input((IMG_SIZE, IMG_SIZE, 3))
    x = data_augment(inputs)                            # train-only augmentation
    x = layers.Rescaling(1.0 / 255)(x)
    x = layers.Normalization(axis=-1, mean=DN_MEAN,
                             variance=[s ** 2 for s in DN_STD])(x)
    x = base_model(x, training=False)              # BN stays in inference mode
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.3)(x)
    outputs = layers.Dense(n_classes, activation="softmax")(x)

    m = models.Model(inputs, outputs, name="densenet121_transfer")

    m.compile(optimizer=tf.keras.optimizers.Adam(HEAD_LR),
              loss="sparse_categorical_crossentropy", metrics=["accuracy"])
    return m

model = build_densenet()

print(f"backbone layers: {len(base_model.layers)} | trainable now: {base_model.trainable}")

model.summary()

"""## Phase 1 — train the head with the backbone frozen

With the backbone frozen, only the new head learns, at the higher learning rate, which is faster.

Fine-tuning a backbone against a *random* head would send large, noisy gradients into the pre-trained weights. Instead the model will first be prepared with a frozen backbone and later receive a fine-tuning in phase 2 (standard two-stage transfer-learning recipe).

"""

# Phase 1: train only the head (backbone frozen). Class weights on; watch val_loss.
head_epochs = 2 if SMOKE_TEST else HEAD_EPOCHS
cbs_head = [callbacks.EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True)]
t0 = time.time()
hist_head = model.fit(train_ds,
                      validation_data=val_ds,
                      epochs=head_epochs,
                      class_weight=class_weight,
                      callbacks=cbs_head,
                      verbose=1)

print(f"\n[phase 1] head warm-up: {len(hist_head.history['loss'])} epochs in {time.time()-t0:.0f}s"
      f" | best val_accuracy = {max(hist_head.history['val_accuracy']):.3f}")

"""## Phase 2 — fine-tune the backbone at a low learning rate

Unfreeze the DenseNet backbone and continue training at a lower learning rate, so the
pre-trained features adapt gently to leaf textures instead of being overwritten. We keep the BatchNormalization layers frozen (a standard fine-tuning safeguard): their ImageNet running statistics
are reliable. Early stopping on `val_loss`
restores the best epoch.

Letting the deeper convolutional filters specialise to the disease textures is where transfer learning earns most of its gain over a frozen backbone.
"""

# Phase 2: unfreeze the backbone (keep BatchNorm frozen), recompile at a low LR, fine-tune.
base_model.trainable = True

for layer in base_model.layers:
    if isinstance(layer, layers.BatchNormalization):
        layer.trainable = False        # keep ImageNet BN stats -> stable fine-tuning

n_trainable = sum(1 for l in base_model.layers if l.trainable)

print(f"backbone trainable layers (excluding frozen BN): {n_trainable} / {len(base_model.layers)}")

model.compile(
    optimizer=tf.keras.optimizers.Adam(FT_LR),     # low LR: don't overwrite the pre-trained weights
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
    )

ft_epochs = 2 if SMOKE_TEST else FT_EPOCHS

cbs_ft = [
    callbacks.EarlyStopping(
        monitor="val_loss",
        patience=4,
        restore_best_weights=True
        ),
    callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=2,
        min_lr=1e-7),
]

t0 = time.time()

hist_ft = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=ft_epochs,
    class_weight=class_weight,
    callbacks=cbs_ft,
    verbose=1
    )

print(f"\n[phase 2] fine-tune: {len(hist_ft.history['loss'])} epochs in {time.time()-t0:.0f}s"
      f" | best val_accuracy = {max(hist_ft.history['val_accuracy']):.3f}")

# stitch the two phases into one history for the learning curves below
#h = {k: hist_head.history[k] + hist_ft.history[k] for k in hist_head.history}
#phase1_len = len(hist_head.history["loss"])   # x-position of the freeze -> fine-tune boundary

# stitch the two phases into one history for the learning curves below
dn_history = {k: hist_head.history[k] + hist_ft.history[k] for k in hist_head.history}
phase1_len = len(hist_head.history["loss"])   # x-position of the freeze -> fine-tune boundary

"""## Save model to Google Drive so it is available without need to run the training process."""

model.save(DRIVE_DIR / "densenet121.keras")

"""## Optional: load a saved model

The cell below is **commented out on purpose**. Leave it as-is for the normal "Run all" flow (train +
evaluate a fresh model). **Uncomment it** to additionally load a model from Drive; the evaluation
section will then run on the loaded model too.

*Zum Aktivieren einfach die beiden Code-Zeilen in der nächsten Zelle einkommentieren.*

"""

# === OPTIONAL: load a previously saved model, then evaluate it too ===
# Normally COMMENTED OUT so "Run all" just trains + evaluates a fresh model.
# Uncomment the two lines to ALSO evaluate a saved model (change the filename if needed).
# The evaluation section picks it up automatically.

#loaded_model = tf.keras.models.load_model(DRIVE_DIR / "densenet121.keras")
#print("Loaded model:", loaded_model.name)



"""## Evaluation (applied to every available model)

> Blockzitat einfügen



`evaluate_model()` bundles all evaluation steps in one place so the exact same analysis runs on each
model:

1. **learning curves** — only when a training `history` is passed (a loaded model has none);
2. **prediction** pass over the validation set;
3. headline **macro-F1** and **accuracy**;
4. **per-class recall** (worst-first, where the imbalance bites);
5. full **classification report**;
6. row-normalised **confusion matrix**.

The driver cell then calls it on the freshly trained model and — if the load cell above was
uncommented — on the loaded model as well.

"""

# One reusable evaluation routine -> identical steps for every model.
def evaluate_model(model, title, history=None, phase_boundary=None):
    """Run every evaluation step on `model` against the validation set (val_ds / yi_val).

    history / phase_boundary are OPTIONAL: pass them for a freshly trained model to also draw the
    learning curves; omit them (e.g. for a loaded model) and that step is skipped.
    Returns (metrics_dict, per_class_dataframe).
    """
    print("=" * 72)
    print(f"Evaluation: {title}")
    print("=" * 72)

    # 1) learning curves - only when a training history is available
    if history is not None:
        fig, ax = plt.subplots(1, 2, figsize=(12, 4))
        ax[0].plot(history["accuracy"], label="train"); ax[0].plot(history["val_accuracy"], label="val")
        ax[1].plot(history["loss"], label="train");     ax[1].plot(history["val_loss"], label="val")
        if phase_boundary is not None:
            for a in ax:
                a.axvline(phase_boundary - 0.5, ls="--", c="grey", lw=1)
        ax[0].set_title("Accuracy"); ax[0].set_xlabel("epoch"); ax[0].legend()
        ax[1].set_title("Loss");     ax[1].set_xlabel("epoch"); ax[1].legend()
        plt.suptitle(f"{title} - learning curves (dashed = fine-tuning starts)")
        plt.tight_layout(); plt.show()
    else:
        print("(no training history -> skipping learning curves)\n")

    # 2) predict the validation set once
    y_true = yi_val
    y_prob = model.predict(val_ds, verbose=0)
    y_pred = y_prob.argmax(axis=1)

    # 3) headline metrics (macro-F1 is the one that matters under 36:1 imbalance)
    mf1 = f1_score(y_true, y_pred, average="macro", zero_division=0)
    acc = accuracy_score(y_true, y_pred)

    print(f"{title}:  macro-F1 = {mf1:.3f}   accuracy = {acc:.3f}\n")

    # 4) per-class recall, sorted worst-first
    rec = recall_score(y_true, y_pred, average=None, labels=range(n_classes), zero_division=0)
    per_class = (pd.DataFrame({
        "class": class_names,
        "recall": rec,
        "val_images": np.bincount(y_true, minlength=n_classes
                                  )})
                 .sort_values("recall"))

    print("Five hardest classes (lowest recall):")
    print(per_class.head().to_string(index=False))
    print("\nFive easiest classes (highest recall):")
    print(per_class.tail().to_string(index=False))

    # 5) full per-class breakdown
    print("\n" + classification_report(
        y_true, y_pred,
        target_names=class_names,
        digits=3,
        zero_division=0
        ))

    # 6) row-normalised confusion matrix (diagonal = per-class recall)
    cm = confusion_matrix(y_true, y_pred, labels=range(n_classes)).astype(float)
    cm_norm = np.divide(cm, cm.sum(axis=1, keepdims=True),
                        out=np.zeros_like(cm), where=cm.sum(axis=1, keepdims=True) > 0)
    plt.figure(figsize=(10, 8))
    sns.heatmap(cm_norm, cmap="viridis", vmin=0, vmax=1, square=True,
                xticklabels=class_names, yticklabels=class_names,
                cbar_kws={"shrink": 0.7, "label": "fraction of true class"})
    plt.xticks(rotation=90, fontsize=7); plt.yticks(rotation=0, fontsize=7)
    plt.xlabel("predicted"); plt.ylabel("true (diagonal = recall)")
    plt.title(f"{title} - row-normalised confusion matrix (validation set)")
    plt.tight_layout(); plt.show()

    return {"macro_F1": mf1, "accuracy": acc}, per_class

# Run the evaluation. The freshly trained model takes priority.
# The loaded model is only used as fallback when no fresh model is available.
# Both are optional.
results = {}
per_class_tables = {}

# Is a freshly trained model present?
try:
    model, dn_history, phase1_len
    _have_fresh = True
except NameError:
    _have_fresh = False

# Is a loaded model present? (only if the load cell above was uncommented)
try:
    loaded_model
except NameError:
    loaded_model = None

if _have_fresh:
    # Prefer the freshly trained model -> evaluate it with learning curves.
    name_new = "DenseNet-121 (freshly trained)"
    results[name_new], per_class_tables[name_new] = evaluate_model(
        model, name_new, history=dn_history, phase_boundary=phase1_len)
    if loaded_model is not None:
        print("A loaded model is also in memory, but a freshly trained model takes "
              "priority -> the loaded model is NOT evaluated.")
elif loaded_model is not None:
    # Fallback: no fresh model, so evaluate the loaded one (no history -> no curves).
    name_loaded = "DenseNet-121 (loaded from Drive)"
    results[name_loaded], per_class_tables[name_loaded] = evaluate_model(
        loaded_model, name_loaded)
else:
    print("Nothing to evaluate: neither a trained nor a loaded model is available.")

# Side-by-side summary of every model that was evaluated (sorted by macro-F1)
summary = (pd.DataFrame(results).T[["macro_F1", "accuracy"]]
           .sort_values("macro_F1").round(3))

print("Validation-set comparison:\n")
print(summary.to_string())