# -*- coding: utf-8 -*-
"""plant-resnet50-kaggle-shared.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZn1Zah8I7dflV48v9W3eSDr35vR_dQA

### Liora plant project - resnet50 - kaggle notebook

**1. GPU for Kaggle**

Change the settings to exploit GPU. How: Settings > Accelerator > select GPU.

**2. Download data and load packages**
"""

### Load the data sets
# note: this dataset contains images of plants both with and without disease
import kagglehub

# Download latest version
path = kagglehub.dataset_download("abdallahalidev/plantvillage-dataset")

print("Path to dataset files:", path)

# Commented out IPython magic to ensure Python compatibility.
# load basic packages
# linear algebra and data
import numpy as np
import pandas as pd
# plots
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns
# paths and small utilities
from pathlib import Path
import collections

# sklearn: used for the stratified, file-level train/val/test split
from sklearn.model_selection import train_test_split
# for visualizing
from sklearn.metrics import classification_report, confusion_matrix

# Imports for model building
import tensorflow as tf
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Dense
#from tensorflow.keras.layers import Conv2D
#from tensorflow.keras.layers import MaxPooling2D
#from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import GlobalAveragePooling2D
from tensorflow.keras.layers import Dropout
# checkpoints to control training process
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, EarlyStopping

# Imports for image transformations
from tensorflow.keras.layers import Rescaling
from tensorflow.keras.layers import RandomFlip
from tensorflow.keras.layers import RandomZoom
from tensorflow.keras.layers import RandomRotation
from tensorflow.keras.layers import RandomTranslation

# Imports for using a pre-trained model: resnet50
from keras.applications.resnet import ResNet50
from keras.applications.resnet import preprocess_input, decode_predictions

# grad-cam and shap
import os
import shap
# optional(?):
# deterministic output wherever possible for reproducibility
tf.config.experimental.enable_op_determinism()

# grad-cam conv layers detection
from tensorflow.keras.layers import Conv2D

"""**3. Creating data set with tensorflow**"""

# Path to the colour images
SOURCE_DIR = Path(path) / "plantvillage dataset" / "color"

# Split ratios
TRAIN_RATIO = 0.70
VAL_RATIO   = 0.15
TEST_RATIO  = 0.15

# original image size 256x256
# resize to 224x224 for resnet input
img_height = 224
img_width  = 224

# batch size and seed
batch_size = 32
seed = 123

# Valid image extensions (used when enumerating files for the split)
IMG_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".gif", ".tif", ".tiff"}

# use tf.keras.utils.image_dataset_from_directory to crete dataset
# creates labels from file directories
# note: creation of train/val split possible here

dataset = tf.keras.utils.image_dataset_from_directory(
    SOURCE_DIR,               # path to colour images
    labels="inferred",        # labels from the directory structure
    image_size=(img_height, img_width),
    batch_size=batch_size,
    seed=seed
)

class_names = dataset.class_names
num_classes = len(class_names)
print(num_classes)
### 38 classes (full dataset, before the split)

# --- Build the file-level, stratified split ---
# Enumerate every image path and its integer label directly from the class folders.
# (Done with pathlib so it does not depend on any loader internals; the stray-file
# filter matches what image_dataset_from_directory counts.)
class_to_idx = {name: i for i, name in enumerate(class_names)}
all_paths, all_labels = [], []
for name in class_names:
    for f in sorted((SOURCE_DIR / name).iterdir()):
        if f.is_file() and f.suffix.lower() in IMG_EXTS:
            all_paths.append(str(f))
            all_labels.append(class_to_idx[name])
all_paths  = np.array(all_paths)
all_labels = np.array(all_labels)
assert len(np.unique(all_labels)) == num_classes
print(f"Enumerated {len(all_paths)} images across {num_classes} classes")

# 1) carve off the TEST set (stratified)
train_paths, test_paths, train_labels, test_labels = train_test_split(
    all_paths, all_labels,
    test_size=TEST_RATIO,
    stratify=all_labels,
    random_state=seed,
)

# 2) carve the VALIDATION set out of the remainder (stratified)
val_relative = VAL_RATIO / (TRAIN_RATIO + VAL_RATIO)   # 0.15 / 0.85
train_paths, val_paths, train_labels, val_labels = train_test_split(
    train_paths, train_labels,
    test_size=val_relative,
    stratify=train_labels,
    random_state=seed,
)

# --- Turn each split's file list into a tf.data pipeline ---
# Images are decoded, resized to (img_height, img_width) and kept as float32 in the
# [0, 255] range (same as image_dataset_from_directory). Normalization is NOT applied
# here: it is a model layer (see the Normalizing section below).
AUTOTUNE = tf.data.AUTOTUNE

def load_and_resize(path, label):
    img = tf.io.read_file(path)
    img = tf.io.decode_image(img, channels=3, expand_animations=False)
    img.set_shape([None, None, 3])
    img = tf.image.resize(img, [img_height, img_width])   # float32, [0,255]
    return img, label

def make_dataset(paths, labels, training=False):
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    if training:
        # full per-epoch shuffle of the training files
        ds = ds.shuffle(len(paths), seed=seed, reshuffle_each_iteration=True)
    ds = ds.map(load_and_resize, num_parallel_calls=AUTOTUNE)
    ds = ds.batch(batch_size)
    return ds

train_ds = make_dataset(train_paths, train_labels, training=True)
val_ds   = make_dataset(val_paths,   val_labels,   training=False)
test_ds  = make_dataset(test_paths,  test_labels,  training=False)

"""**4. Defining augementation**

Note that we define the augmentation here but include it as an input while defining the model later.
"""

##### augmentation layer (applied inside the model, at training time only)
#def data_augmentation(x):
#  x = RandomFlip("horizontal", input_shape=(img_height, img_width, 3))(x)   # horizontal flip
#  x = RandomRotation(0.1)(x) # rotation
#  x = RandomZoom(0.1)(x) # zoom
#  return x
#### Will be done later

"""**5. Normalizing**"""

#### Normalization as a layer: included as the FIRST layer of the model later, so
#### train/val/inference all use identical scaling and the datasets themselves can
#### stay raw. Pixel values are 0..255, so divide by 255 (max maps to exactly 1.0).
#normalization_layer = Rescaling(1./255)
# caused problems -> omitted

"""**6. Building ResNet50 Model**"""

#### same preprocessing as pre-trained model
train_ds = train_ds.map(lambda x, y: (preprocess_input(x), y))
val_ds = val_ds.map(lambda x, y: (preprocess_input(x), y))

# computing class weights
from sklearn.utils.class_weight import compute_class_weight
class_weights = compute_class_weight(class_weight='balanced',
                                     classes=np.unique(train_labels),
                                     y=train_labels)
# create dictonary for class weights
class_weights = dict(zip(np.unique(train_labels), class_weights))
#class_weights
# save class weights
np.save('class_weights.npy', class_weights)

# resnet50 model
#base_model = ResNet50(weights='imagenet', include_top=False)
base_model = ResNet50(
    include_top=False,
    weights='imagenet',
    input_shape=(224, 224, 3)
)
# Freeze the layers of resnet
base_model.trainable = False
# unfreeze last 4 layers
#for layer in base_model.layers[-4:]:
#    layer.trainable = True

# Model creation using the Functional API
inputs = Input(shape=(224, 224, 3))

# Apply augmentations
#x = data_augmentation(inputs)
# try augmentation here rather than with function
x = RandomFlip("horizontal")(inputs)   # horizontal flip
x = RandomRotation(0.1)(x) # rotation
x = RandomZoom(0.1)(x) # zoom
#x = Rescaling(1./255)(x) #skip normalizing since preprocess for resnet model applied
#x = RandomTranslation(height_factor=0.1, width_factor=0.1)(x)


# Build the model
x = base_model(x, training=False) # training=False
x = GlobalAveragePooling2D()(x)
x = Dense(1024, activation='relu')(x)
x = Dropout(rate=0.2)(x)
x = Dense(512, activation='relu')(x)
x = Dropout(rate=0.2)(x)
outputs = Dense(num_classes, activation='softmax')(x)

model = Model(inputs=inputs, outputs=outputs)

# compile model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# model summary
model.summary()

### use buffered prefetching
# train_ds already shuffles its files each epoch (see make_dataset), so no extra
# shuffle here. The full training set is too large to cache in Colab RAM, so we only
# prefetch it; val/test are smaller and safe to cache in memory.
train_ds = train_ds.prefetch(buffer_size=AUTOTUNE)
val_ds   = val_ds.cache().prefetch(buffer_size=AUTOTUNE)
test_ds  = test_ds.cache().prefetch(buffer_size=AUTOTUNE)

"""**7. Train Model**"""

# early stopping
# if loss does not decrease sufficiently
early_stopping = EarlyStopping(
                                patience=5, # num of epochs when stops wo improve
                                min_delta=0.01, # min change in monitored value
                                mode='min', # minimize monitored value
                                monitor='val_loss',
                                restore_best_weights = True, # keep best weights after
                                verbose = 1)

# callback to save the model
# while training
save = ModelCheckpoint(
    'best_resnet50_2.keras', # save as ...
    save_best_only=True, # always save best model
    monitor='val_accuracy',
    mode='max' # maximize monitored value
)

# callback to reduce the learning rate
# when performance doesnt get better
reduceLR = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.1, # set threshold of variation in the monitored metric
    patience=3,
    min_lr=1e-6
)

# List available physical devices detected by TensorFlow
gpus = tf.config.list_physical_devices('GPU')

# training with defined callbacks
with tf.device('/GPU:0'):
  model_history = model.fit(train_ds,
                            validation_data=val_ds,
                            epochs=10,
                            class_weight=class_weights,
                            callbacks = [reduceLR,
                                       save, early_stopping])

# save model with keras
model.save('resnet50_4.keras')
# save weights
model.save_weights('resnet50_4_weights.weights.h5')

# only on colab
### download to device (home dir is only temporary?)
from google.colab import files

# save h5 and keras model and weights
files.download('resnet50_4.keras')
files.download('resnet50_4_weights.weights.h5')
# download best model from callback
files.download('best_resnet50_2.keras')

# cost function and accuracy curve as a function of the epoch
plt.figure(figsize=(12,4))

plt.subplot(121)
plt.plot(model_history.history['loss'])
plt.plot(model_history.history['val_loss'])
plt.title('Model loss by epoch')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='right')

plt.subplot(122)
plt.plot(model_history.history['accuracy'])
plt.plot(model_history.history['val_accuracy'])
plt.title('Model accuracy by epoch')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='right')
plt.show()

from tensorflow.keras import optimizers

#### fine-tuning
# try unfreeze layers now and train again
for layer in base_model.layers[-4:]:
    layer.trainable = True
# compile model again
model.compile(optimizer=optimizers.Adam(1e-5), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# model.compile(optimizer=keras.optimizers.Adam(1e-5),  loss=keras.losses.BinaryCrossentropy(from_logits=True), metrics=[keras.metrics.BinaryAccuracy()])

base_model.summary(show_trainable=True)

# train for 5 epoch
with tf.device('/GPU:0'):
  model_history = model.fit(train_ds,
                            validation_data=val_ds,
                            epochs=5,
                            class_weight=class_weights,
                            callbacks = [reduceLR,
                                       save, early_stopping])

"""**8. Saving Model**"""

# save model with keras
model.save('resnet50_5.keras')
# save weights
model.save_weights('resnet50_5_weights.weights.h5')

# only on colab
### download to device (home dir is only temporary?)
from google.colab import files

# save h5 and keras model and weights
files.download('resnet50_5.keras')
files.download('resnet50_5_weights.weights.h5')
# download best model from callback
files.download('best_resnet50_2.keras')

# save model with joblib (optional)
import joblib
#path = Path.home() / "/home"
joblib.dump(model, "resnet50_5.joblib")
# save joblib file on colab
#files.download('resnet50_5.joblib')

"""**9. Evaluation**"""

# cost function and accuracy curve as a function of the epoch
plt.figure(figsize=(12,4))

plt.subplot(121)
plt.plot(model_history.history['loss'])
plt.plot(model_history.history['val_loss'])
plt.title('Model loss by epoch')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='right')

plt.subplot(122)
plt.plot(model_history.history['accuracy'])
plt.plot(model_history.history['val_accuracy'])
plt.title('Model accuracy by epoch')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='right')
plt.show()

# Function to get the true labels and model predictions
def get_predictions_and_labels(dataset):
    true_labels = []
    pred_labels = []

    for images, labels in dataset:

        preds = model.predict(images, verbose=0)
        pred_labels.extend(np.argmax(preds, axis=-1))

        true_labels.extend(labels.numpy())

    return np.array(true_labels), np.array(pred_labels)

# Get the true labels and predictions for the validation set
y_true, y_pred = get_predictions_and_labels(val_ds)

# Display the classification report
print(classification_report(y_true, y_pred))

# Display the confusion matrix
plt.figure(figsize=(15, 15))  # Create a large figure for the confusion matrix
cnf_matrix = confusion_matrix(y_true, y_pred, normalize='true')  # Compute the normalized confusion matrix
sns.heatmap(cnf_matrix, cmap='Blues', annot=True, cbar=False, fmt=".2f")  # Plot the confusion matrix as a heatmap

# Test dataset evaluation
model.evaluate(test_ds)

# try again with preprocessed test set
test_ds_pre = test_ds.map(lambda x, y: (preprocess_input(x), y))
model.evaluate(test_ds_pre)

"""**Conclusion for resnet50:** good performance overall with frozen layers, and even better by directly training a few layers of resnet50 (fine-tuning). Maybe the accuracy is lower than our CNN from scratch but grad-cam results better here?

**10. Grad-CAM/SHAP**
"""

# converting to numpy arrays
X = np.array([img.numpy() for img, _ in val_ds.take(2)][0]).astype(np.uint8)
y = np.array([label.numpy() for _, label in val_ds.take(2)][0])

# Select specific images
images = X[:4]
labels = y[:4]

# resize
images2 = []

for img in images:
  img = np.expand_dims(img, axis=0)
  images2.append(img)

def make_gradcam_heatmap(img_array, model, last_conv_layer_name, resnet_layer_name="resnet50", pred_index=None):
    # get resnet50 base model
    resnet_base = model.get_layer(resnet_layer_name)

    # create sub-model to get last conv output from resnet50
    conv_layer = resnet_base.get_layer(last_conv_layer_name)
    resnet_submodel = tf.keras.models.Model(
        inputs=resnet_base.inputs,
        outputs=conv_layer.output
    )

    # collect layers on top of resnet50 in your outer model
    classifier_layers = []
    found_resnet = False
    for layer in model.layers:
        if found_resnet:
            classifier_layers.append(layer)
        if layer.name == resnet_layer_name:
            found_resnet = True

    # compute gradients
    with tf.GradientTape() as tape:
        # pass image through submodel to get feature maps
        conv_outputs = resnet_submodel(img_array)
        tape.watch(conv_outputs)

        # pass feature maps through the rest of the layers
        x = conv_outputs
        for layer in classifier_layers:
            x = layer(x)
        preds = x

        if pred_index is None:
            pred_index = tf.argmax(preds[0])
        class_channel = preds[:, pred_index]

    # calculate gradients of scores w.r.t. con layer
    grads = tape.gradient(class_channel, conv_outputs)

    # weighted average of the gradients for each channel
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    # weight feature maps by gradient importance
    conv_outputs = conv_outputs[0]
    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    # apply ReLU & normalize
    heatmap = tf.maximum(heatmap, 0) / tf.math.reduce_max(heatmap)
    return heatmap.numpy()

def display_gradcam_array_tf(original_img, heatmap, alpha=0.4):
    # overlay Grad-CAM heatmap
    # normalize original image to [0, 1] float32 array
    img = tf.cast(original_img, tf.float32)
    if tf.reduce_max(img) > 1.0:
        img = img / 255.0

    # resize heatmap
    heatmap_tensor = tf.reshape(heatmap, (1, heatmap.shape[0], heatmap.shape[1], 1))
    heatmap_resized = tf.image.resize(heatmap_tensor, (img.shape[0], img.shape[1]))
    heatmap_resized = tf.squeeze(heatmap_resized).numpy()

    # superimpose with jet colormap/palettw
    jet_cmap = plt.get_cmap("jet")
    # apply colormap
    color_heatmap = jet_cmap(heatmap_resized)[:, :, :3]  # Drop alpha channel

    # blend images directly (both are float32 in range [0.0, 1.0])
    superimposed_img = color_heatmap * alpha + img * (1 - alpha)
    superimposed_img = np.clip(superimposed_img, 0.0, 1.0)

    # plot original vs Grad-CAM
    plt.figure(figsize=(10, 5))

    plt.subplot(1, 2, 1)
    plt.imshow(img)
    plt.title("original")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(superimposed_img)
    plt.title("Grad-CAM")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

# convolutional layers of base model
conv_layers_base = [layer.name for layer in base_model.layers if isinstance(layer, Conv2D)]
last_con_layer_base = conv_layers_base[-1]
print(last_con_layer_base)
# we only examine the last conv layer that we trained

for i in images2:
  heatmap = make_gradcam_heatmap(i, model, last_con_layer_base)
  display_gradcam_array_tf(i[0], heatmap)

"""Interpretation:
- note: thes left images are preprocessed for resnet50 input
- model focuses on specific and relevant regions of the image
- convolutional layer extracts complex features
- better classification
- in some pictures we can detect an influence from background(!)
- BUT: this could also mean that the leaf is (mostly) healthy and there are no spots for the model to focus on!!!
"""

# Initialize the SHAP masker
masker = shap.maskers.Image("inpaint_telea", images[0].shape)

# Create the SHAP explainer
explainer = shap.Explainer(model, masker, output_names=class_names)

# Calculate SHAP values for the images we want to explain
shap_values = explainer(images, max_evals=500, outputs=shap.Explanation.argsort.flip[:4])

shap.image_plot(shap_values)

"""Interpretation:
-  note: regions of image highlighted that have a positive or negative impact on the class membership
- read areas are relevant for predicting that plant belongs to a class
- blue areas relevant for predicting that it does not belong to class
- we can see a few biases from the background
"""

